### ISSUE TITLE
타임리프 적용했을 때, html 오류 나는 부분

### ISSUE THREAD

**Issue by LeeSamgsoo** [HalLengWang/HLW#56]
## 작업 내역
- todo_list.html 리스트 출력 시, 왼쪽으로 몰려서 출력 되는 부분
![image](https://github.com/user-attachments/assets/62c9b179-7cf4-49ea-9673-923b679f070c)

- todo_lsit_detail.html 에서 카드 넘기는 페이지네이션이 들어갈 영역이 없음
![image](https://github.com/user-attachments/assets/7cf71cd3-700a-4174-8f43-24e1c857cb33)

- todo_lsit_detail.html 에서 카드 출력 되는 영역이 지정 되어있지 않고, 카드 하나하나 개별 영역으로 떨어져 있어서 카드를 여러 개 출력할 수가 없음
![image](https://github.com/user-attachments/assets/22f1465e-e768-4a61-b204-137acc967b4a)

- todo_list_detail.html 제목 출력, 입력 부분이 이상하게 출력됨
![image](https://github.com/user-attachments/assets/cc7b0fd2-64ae-43f7-8fee-334b65dc3abb)

## TODO
- [x]  todo_list.html 리스트 출력 수정
- [x] todo_lsit_detail.html 페이지네이션 영역 추가
- [x] todo_lsit_detail.html 카드 묶음 출력 영역 추가
- [x] todo_list_detail.html 제목 출력, 입력 부분 수정

## 참고 사항
- 이 이슈는 지우지 마세요
- 담당자(Assignees) 두 분 지정해 놨는데, 이 이슈에서 본인이 할 작업 내역, TODO 고르고 따로 이슈 만들어서 복붙하세요.
- 제가 이 이슈에서 수정할 부분 계속 업데이트 하겠습니다.

**Comment by starlike3279** [comment]
모두 수정했고, 아직 git push하지 않은 상태입니다.
