### ISSUE TITLE
TODO List detail 페이지 수정

### ISSUE THREAD

**Issue by LeeSamgsoo** [HalLengWang/HLW#71]
## 작업 내역
- TODO Card 순서대로 정렬 되게 div 설정
- TODO Card 타이틀 날짜 순서대로 정렬 되게 설정
- 리스트 제목에서 돋보기 제거

## TODO
- [x] todo_list_detail.html에서 페이지 네이션 위치 수정
- [x] 카드 위치 수정
- [x] 카드 검색창 위치 수정
- [x] 카드 타이틀 날짜 정렬
- [x] 리스트 제목에 돋보기 제거
